[package]

name = "piston2d-opengl_graphics"
version = "0.0.16"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"
]
keywords = ["opengl", "graphics", "2d", "piston"]
description = "An OpenGL 2D back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/opengl_graphics.git"
homepage = "https://github.com/PistonDevelopers/opengl_graphics"

[dependencies.piston-texture]
git = "https://github.com/pistondevelopers/texture"
#version = "0.0.1"

[dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"
#version = "0.0.23"

[dependencies.image]
git = "https://github.com/pistondevelopers/image"
default-features = false
#version = "~0.2.0"

[dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"
#version = "0.0.2"

[dependencies.piston-shaders_graphics2d]
git = "https://github.com/pistondevelopers/shaders"
#version = "0.0.0"

[dependencies.freetype-rs]
git = "https://github.com/PistonDevelopers/freetype-rs.git"
#version = "0.0.7"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"
#version = "0.0.9"

[dev-dependencies.piston]
git = "https://github.com/pistondevelopers/piston"
#version = "0.0.0"

[dev-dependencies.pistoncore-sdl2_window]
git = "https://github.com/pistondevelopers/sdl2_window"
#version = "0.0.0"

[dependencies]
libc = "*"

[build-dependencies]
khronos_api = "*"

[lib]

name = "opengl_graphics"
path = "src/lib.rs"

[features]

default = ["image_png"]
image_gif = ["image/gif"]
image_jpeg = ["image/jpeg"]
image_png = ["image/png"]
image_ppm = ["image/ppm"]
image_tga = ["image/tga"]
image_tiff = ["image/tiff"]
image_webp = ["image/webp"]
