[package]

name = "opengl_graphics"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"]

[dependencies.image]

git = "https://github.com/pistondevelopers/image"

[dependencies.gl]

git = "https://github.com/bjz/gl-rs"

[dependencies.texture]

git = "https://github.com/pistondevelopers/texture"

[dependencies.graphics]

git = "https://github.com/pistondevelopers/graphics"

[dependencies.shader_version]

git = "https://github.com/pistondevelopers/shader_version"

[lib]

name = "opengl_graphics"
path = "src/lib.rs"

